allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  '@hono/node-server': 1.19.13
  nodemailer: 9.0.3
  postcss: 8.5.10
  uuid: 11.1.1
